# Generated by Django 5.1.3 on 2025-07-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendance_count',
        ),
    ]
