# Generated by Django 5.1.3 on 2025-07-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='user',
        ),
    ]
