# Generated by Django 5.1.3 on 2025-08-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_testimony_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='event_thumbnails/'),
        ),
    ]
