# Generated by Django 5.1.3 on 2025-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
