# Generated by Django 5.1.5 on 2025-03-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sermon_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
