# Generated by Django 5.1.3 on 2025-07-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveStream',
        ),
    ]
